---
title: "LMS Choral Fundraiser 2020"
output: 
  flexdashboard::flex_dashboard:
    theme: lumen
    logo: img/lion_sm.png
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyr)
library(dplyr)
library(ggthemes)
library(ggplot2)
library(plotly)

sales.dat.sg <- data.frame(
  date = c("2020-01-21", "2020-01-28", "2020-01-29", "2020-01-30", "2020-01-31"),
 # n.orders = c(22, 27),
  sixth.grade = c(0, 8, 8, 9, 10), #6 is a guess
  other.grades = c(0, 22, 27, 27, 27), 
  satterfields = c(0,0,0,11, 11),
 stringsAsFactors = FALSE
) %>%
  mutate(n.orders = sixth.grade + other.grades+satterfields,
         money.raised = n.orders*5)

sales.dat.loid <- data.frame(
  date = c("2020-02-03", "2020-02-05", "2020-02-07"),
 # n.orders = c(22, 27),
 chamber.choir = c(0, 3,10),
 adv.choir = c(0,10, 32),
 debut.voix = c(0,0,0),
 luna.voce = c(0,3,9),
 vox.gentum = c(0,0,0),
  #satterfields = c(0,0,0,11, 11),
 stringsAsFactors = FALSE
) %>%
  mutate(n.orders = chamber.choir + adv.choir+debut.voix+luna.voce+vox.gentum,
         money.raised = n.orders*5)

sales.dat <- sales.dat.loid

trip.cost <- 150
```

Column {data-width=75%} 
-----------------------------------------------------------------------

### Overall Progress to Goal

```{r warning=FALSE}
goal.sg <- 900
goal.loid <- 1000

goal <- goal.loid

prog.dat2 <- sales.dat %>%
  gather(key = "choir", value = "n.sales", chamber.choir:vox.gentum) %>%
  mutate(sales.money = n.sales*5) %>%
  select(-n.sales) %>%
  spread(key = choir, value = sales.money)

#  mutate(sixth.grade.sales = sixth.grade*5,
 #        other.grades.sales = other.grades*5,
  #       satterfield.sales = satterfields*5)

plot_ly(prog.dat2, x = ~as.Date(date), y = ~chamber.choir, name = 'Chamber Choir', 
        type = 'scatter', mode = 'none', stackgroup = 'one') %>%
  add_trace(y = ~adv.choir, name = 'Adv Choir') %>%
  add_trace(y = ~debut.voix, name = 'Debut Voix') %>%
  add_trace(y = ~luna.voce, name = 'Luna Voce') %>%
  add_trace(y = ~vox.gentum, name = 'Vox Gentum') %>%
  add_trace(y = goal, mode = "lines", name = "Fundraising Goal", stackgroup = NA) %>%
  layout(title = list(text="LMS Spring Fundraiser",
                      font = list(size =48)),
         xaxis = list(title = "",
                      showgrid = FALSE),
         yaxis = list(title = "Money Raised",
                      showgrid = TRUE),
         margin = list(t=120))
```


Column {data-width=25%}
-----------------------------------------------------------------------

### Days Remaining

```{r}
this.day <- Sys.Date()
end.date.sg <- as.Date("2020-02-04")
end.date.loid <- as.Date("2020-02-18")
end.date <- end.date.loid
days.remaining <- as.numeric(end.date-Sys.Date())+1

valueBox(days.remaining, 
         color = ifelse(days.remaining > 6, "info", ifelse(days.remaining > 3, "warning", "danger")), 
         icon = "fa-calendar-alt")

```

### Percent to Goal

```{r}

goal.percent <- sales.dat %>%
filter(date == max(as.Date(date) )) %>%
.$money.raised/goal

perc.f <- paste0(round(goal.percent*100, 1), "%")


valueBox(perc.f, 
         color = ifelse(goal.percent < 0.3, "danger", ifelse(goal.percent <0.6, "warning", "success")), 
         icon = ifelse(goal.percent < 0.3, "fa-thermometer-quarter", 
                       ifelse(goal.percent <0.6, "fa-thermometer-half", "fa-thermometer-full")))

```


### Number of Students Funded

```{r}

num.students <- sales.dat %>%
filter(date == max(as.Date(date) )) %>%
.$money.raised/trip.cost

stud.f <- round(num.students, 0)


valueBox(stud.f, icon = "fa-user-friends")
```



